version: '2'

services:
  idena:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - CONTAINER_TIMEZONE="Europe/Moscow"
    image: postarc/idena:latest
#    command: idena
    volumes:
      - ./data/idena:/root/.idena
    ports:
      - 40403:40403
      - 40404:40404
      - 9009:9009
